# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-26 13:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALL_cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_dbf_id', models.CharField(default='', max_length=200, verbose_name='hsreplay_dbf_ID')),
                ('card_id', models.CharField(default='', max_length=200, verbose_name='hsreplay_dbf_ID')),
                ('card_name', models.CharField(default='', max_length=200, verbose_name='卡牌中文名')),
                ('car_en_name', models.CharField(default='', max_length=200, verbose_name='卡牌英文名')),
                ('car_text', models.CharField(default='', max_length=200, verbose_name='卡牌文字')),
                ('car_type', models.CharField(default='', help_text='（随从，法术，武器，英雄）', max_length=200, verbose_name='卡牌类型')),
                ('car_rarity', models.CharField(default='', help_text='（基础卡，普通，稀有，史诗，传说）', max_length=200, verbose_name='卡牌稀有度')),
                ('car_cardClass', models.CharField(default='', help_text='战士，法师，盗贼，猎人，德鲁伊，萨满，圣骑士，牧师，术士', max_length=200, verbose_name='卡牌职业')),
                ('car_cost', models.CharField(default='', max_length=200, verbose_name='卡牌费用')),
                ('is_standard', models.BooleanField(default=False, max_length=200, verbose_name='是否是标准环境卡牌')),
                ('car_set', models.CharField(default='', help_text='属于哪个扩展包', max_length=200, verbose_name='属于扩展包')),
                ('car_race', models.CharField(default='', help_text='种族', max_length=200, verbose_name='种族')),
                ('car_mechanism', models.CharField(default='', help_text='战吼', max_length=200, verbose_name='机制')),
                ('car_image', models.CharField(default='', help_text='图片', max_length=500, verbose_name='图片')),
                ('car_min_image', models.CharField(default='', help_text='缩略图', max_length=500, verbose_name='缩略图')),
            ],
            options={
                'verbose_name': '所有卡牌，来自hsreplay',
                'verbose_name_plural': '所有卡牌，来自hsreplay',
            },
        ),
    ]
