# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-26 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190726_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_cards',
            name='car_cardClass',
            field=models.CharField(blank=True, default='', help_text='战士，法师，盗贼，猎人，德鲁伊，萨满，圣骑士，牧师，术士', max_length=200, verbose_name='卡牌职业'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_cost',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='卡牌费用'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_en_name',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='卡牌英文名'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_image',
            field=models.CharField(blank=True, default='', help_text='图片', max_length=500, verbose_name='图片'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_mechanism',
            field=models.CharField(blank=True, default='', help_text='战吼', max_length=200, verbose_name='机制'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_min_image',
            field=models.CharField(blank=True, default='', help_text='缩略图', max_length=500, verbose_name='缩略图'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_race',
            field=models.CharField(blank=True, default='', help_text='种族', max_length=200, verbose_name='种族'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_rarity',
            field=models.CharField(blank=True, default='', help_text='（基础卡，普通，稀有，史诗，传说）', max_length=200, verbose_name='卡牌稀有度'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_set',
            field=models.CharField(blank=True, default='', help_text='属于哪个扩展包', max_length=200, verbose_name='属于扩展包'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_text',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='卡牌文字'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_type',
            field=models.CharField(blank=True, default='', help_text='（随从，法术，武器，英雄）', max_length=200, verbose_name='卡牌类型'),
        ),
    ]
