# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20190726_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_cards',
            name='car_cardClass',
            field=models.CharField(blank=True, default='', help_text='战士(WARRIOR)，法师(MAGE)，盗贼(ROGUE)，猎人(HUNTER)，德鲁伊(DRUID)，萨满(SHAMAN)，圣骑士(PALADIN)，牧师(PRIEST)，术士(WARLOCK)', max_length=200, verbose_name='卡牌职业'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_race',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='种族'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_rarity',
            field=models.CharField(blank=True, default='', help_text='（基础卡(FREE)，普通(COMMON)，稀有(RARE)，史诗(EPIC)，传说(LEGENDARY)）', max_length=200, verbose_name='卡牌稀有度'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_set',
            field=models.CharField(blank=True, default='', help_text='基础卡（CORE）,经典（EXPERT1），暗影崛起（DALARAN），拉斯塔哈的大乱斗（TROLL），砰砰计划（BOOMSDAY），女巫森林（GILNEAS），狗头人与地下世界（LOOTAPALOOZA），冰封的王座（ICECROWN），勇闯安戈洛（UNGORO），龙争虎斗加基森（GANGS），卡拉赞之夜（KARA），上古之神的低语（OG），探险者协会（LOE），冠军的试炼（TGT），黑石山的火焰（BRM），地精大战侏儒（GVG），纳克萨玛斯（NAXX），荣誉室（HOF）', max_length=200, verbose_name='属于扩展包'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='car_type',
            field=models.CharField(blank=True, default='', help_text='（随从(MINION)，法术(SPELL)，武器(WEAPON)，英雄(HERO)）', max_length=200, verbose_name='卡牌类型'),
        ),
    ]
