# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 11:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auto_20190726_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_cardClass',
            new_name='card_cardClass',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_cost',
            new_name='card_cost',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_en_name',
            new_name='card_en_name',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_image',
            new_name='card_image',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_mechanism',
            new_name='card_mechanism',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_min_image',
            new_name='card_min_image',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_race',
            new_name='card_race',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_rarity',
            new_name='card_rarity',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_set',
            new_name='card_set',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_text',
            new_name='card_text',
        ),
        migrations.RenameField(
            model_name='all_cards',
            old_name='car_type',
            new_name='card_type',
        ),
        migrations.AddField(
            model_name='all_cards',
            name='card_Deck_Deck',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='套牌总数', max_digits=10, verbose_name='卡组数'),
        ),
        migrations.AddField(
            model_name='all_cards',
            name='card_count_Deck',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='套牌中平均携带数量', max_digits=10, verbose_name='卡组张数'),
        ),
        migrations.AddField(
            model_name='all_cards',
            name='card_popularity_Deck',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='套牌中至少包含一张该卡的概率', max_digits=10, verbose_name='卡组出现概率'),
        ),
        migrations.AddField(
            model_name='all_cards',
            name='card_popularity_play_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='在所有牌中这张卡牌被打出的概率', max_digits=10, verbose_name='打出卡牌中占比'),
        ),
        migrations.AddField(
            model_name='all_cards',
            name='card_total_play_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='这张卡牌打出的次数', max_digits=10, verbose_name='打出次数'),
        ),
        migrations.AddField(
            model_name='all_cards',
            name='card_winrate_Deck',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='携带这张卡组的平均概率', max_digits=10, verbose_name='卡组胜率'),
        ),
        migrations.AddField(
            model_name='all_cards',
            name='card_winrate_play_out',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='在任何时刻打出的卡牌的平均胜率', max_digits=10, verbose_name='打出胜率'),
        ),
        migrations.AddField(
            model_name='all_cards',
            name='updatetime',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
