# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_auto_20190729_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_cards',
            name='card_Deck_Deck',
            field=models.FloatField(blank=True, default=0, help_text='套牌总数', verbose_name='卡组数'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='card_count_Deck',
            field=models.FloatField(blank=True, default=0, help_text='套牌中平均携带数量', verbose_name='卡组张数'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='card_popularity_Deck',
            field=models.FloatField(blank=True, default=0, help_text='套牌中至少包含一张该卡的概率', verbose_name='卡组出现概率'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='card_popularity_play_out',
            field=models.FloatField(blank=True, default=0, help_text='在所有牌中这张卡牌被打出的概率', verbose_name='打出卡牌中占比'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='card_total_play_out',
            field=models.FloatField(blank=True, default=0, help_text='这张卡牌打出的次数', verbose_name='打出次数'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='card_winrate_Deck',
            field=models.FloatField(blank=True, default=0, help_text='携带这张卡组的平均概率', verbose_name='卡组胜率'),
        ),
        migrations.AlterField(
            model_name='all_cards',
            name='card_winrate_play_out',
            field=models.FloatField(blank=True, default=0, help_text='在任何时刻打出的卡牌的平均胜率', verbose_name='打出胜率'),
        ),
    ]
