# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-07-29 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_auto_20190729_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_name', models.CharField(default='', max_length=200, verbose_name='卡组名称')),
                ('Group_id', models.IntegerField(blank=True, default=0, max_length=50000, verbose_name='卡组ID')),
                ('Group_player_class', models.IntegerField(blank=True, default=0, help_text='什么职业的卡组id', verbose_name='类别ID')),
                ('Group_player_class_name', models.CharField(blank=True, default=0, help_text='什么职业的卡组', max_length=200, verbose_name='类别')),
                ('Group_as_of', models.CharField(blank=True, default=0, help_text='卡组加入更新时间', max_length=200, verbose_name='更新时间')),
                ('Group_components', models.CharField(blank=True, default=0, help_text='卡组关键组成', max_length=200, verbose_name='卡组关键组成')),
                ('Group_URL', models.CharField(blank=True, default=0, help_text='卡组关键组成', max_length=200, verbose_name='卡组关键组成')),
            ],
        ),
    ]
