# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-02 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_card_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card_group',
            options={'verbose_name': '卡组原型，信息', 'verbose_name_plural': '卡组原型，信息'},
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_pct_of_class',
            field=models.FloatField(blank=True, default=0, help_text='近七天原型占该职业的套牌的百分比', verbose_name='近七天原型占该职业的套牌的百分比'),
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_pct_of_total',
            field=models.FloatField(blank=True, default=0, help_text='近七天原型占所有的套牌的百分比', verbose_name='近七天原型占所有的套牌的百分比'),
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_recent3_average_hot',
            field=models.FloatField(blank=True, default=0, help_text='原型近三天的平均热度', verbose_name='原型近三天的平均热度'),
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_recent3_average_win',
            field=models.FloatField(blank=True, default=0, help_text='原型近三天的平均胜率', verbose_name='原型近三天的平均胜率'),
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_total_games',
            field=models.FloatField(blank=True, default=0, help_text='近七天原型总对局', verbose_name='近七天原型总对局'),
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_win_rate',
            field=models.FloatField(blank=True, default=0, help_text='近七天原型总对局胜率', verbose_name='近七天原型总对局胜率'),
        ),
        migrations.AlterField(
            model_name='card_group',
            name='Group_URL',
            field=models.CharField(blank=True, default=0, help_text='卡组URL', max_length=200, verbose_name='原型URL'),
        ),
        migrations.AlterField(
            model_name='card_group',
            name='Group_components',
            field=models.CharField(blank=True, default=0, help_text='卡组关键组成', max_length=200, verbose_name='原型关键组成'),
        ),
        migrations.AlterField(
            model_name='card_group',
            name='Group_id',
            field=models.IntegerField(blank=True, default=0, verbose_name='原型ID'),
        ),
        migrations.AlterField(
            model_name='card_group',
            name='Group_name',
            field=models.CharField(default='', max_length=200, verbose_name='原型名称'),
        ),
    ]
