# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-02 13:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0011_auto_20190802_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_duikang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_id', models.CharField(default='', help_text='原型名称', max_length=200, verbose_name='原型名称')),
                ('hit_Group_id', models.CharField(default='', help_text='原型对抗名称', max_length=200, verbose_name='原型对抗名称')),
                ('total_games', models.FloatField(blank=True, default=0, help_text='近七天原型对抗总对局', verbose_name='近七天原型对抗总对局')),
                ('win_rate', models.FloatField(blank=True, default=0, help_text='近七天原对抗胜率', verbose_name='近七天原对抗胜率')),
                ('upda_time', models.CharField(blank=True, default=0, help_text='原型对局信息更新时间', max_length=200, verbose_name='原型对局信息更新时间')),
            ],
            options={
                'verbose_name': '卡组原型，信息',
                'verbose_name_plural': '卡组原型，信息',
            },
        ),
    ]
