# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-02 21:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0012_card_duikang'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card_pct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Group_id', models.IntegerField(blank=True, default=0, verbose_name='原型ID')),
                ('Group_pct_of_class', models.FloatField(blank=True, default=0, help_text='近七天原型占该职业的套牌的百分比', verbose_name='近七天原型占该职业的套牌的百分比')),
                ('Group_pct_of_total', models.FloatField(blank=True, default=0, help_text='近七天原型占所有的套牌的百分比', verbose_name='近七天原型占所有的套牌的百分比')),
                ('Group_total_games', models.FloatField(blank=True, default=0, help_text='近七天原型总对局', verbose_name='近七天原型总对局')),
                ('Group_win_rate', models.FloatField(blank=True, default=0, help_text='近七天原型总对局胜率', verbose_name='近七天原型总对局胜率')),
                ('Group_as_of_info', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='原型对局信息更新时间', max_length=100, null=True, verbose_name='原型对局信息更新时间')),
            ],
            options={
                'verbose_name': '卡组原型，热度，占比',
                'verbose_name_plural': '卡组原型，热度，占比',
            },
        ),
        migrations.CreateModel(
            name='Deck_hit_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deck_deck_id', models.CharField(default='', help_text='卡组id', max_length=200, verbose_name='卡组id')),
                ('Deck_hit_DRUID', models.FloatField(default=0, help_text='卡组对战德鲁伊胜率', verbose_name='卡组对战德鲁伊胜率')),
                ('Deck_hit_HUNTER', models.FloatField(default=0, help_text='卡组对战猎人胜率', verbose_name='卡组对战猎人胜率')),
                ('Deck_hit_MAGE', models.FloatField(default=0, help_text='卡组对战法师胜率', verbose_name='卡组对战法师胜率')),
                ('Deck_hit_WARLOCK', models.FloatField(default=0, help_text='卡组对战术士胜率', verbose_name='卡组对战术士胜率')),
                ('Deck_hit_PALADIN', models.FloatField(default=0, help_text='卡组对战骑士胜率', verbose_name='卡组对战骑士胜率')),
                ('Deck_hit_PRIEST', models.FloatField(default=0, help_text='卡组对战牧师胜率', verbose_name='卡组对战牧师胜率')),
                ('Deck_hit_ROGUE', models.FloatField(default=0, help_text='卡组对战潜行者胜率', verbose_name='卡组对战潜行者胜率')),
                ('Deck_hit_SHAMAN', models.FloatField(default=0, help_text='卡组对战萨满胜率', verbose_name='卡组对战萨满胜率')),
                ('Deck_hit_WARRIOR', models.FloatField(default=0, help_text='卡组对战战士胜率', verbose_name='卡组对战战士胜率')),
                ('Deck_UP_time', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='卡组对抗更新时间', max_length=100, null=True, verbose_name='卡组对抗更新时间')),
            ],
            options={
                'verbose_name': '套牌对抗胜率',
                'verbose_name_plural': '套牌对抗胜率',
            },
        ),
        migrations.CreateModel(
            name='Deck_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deck_archetype_id', models.CharField(default='', help_text='卡组原型', max_length=200, verbose_name='卡组原型')),
                ('Deck_avg_game_length_seconds', models.FloatField(default=0, help_text='30天平均对局时长', verbose_name='30天平均对局时长')),
                ('Deck_avg_num_player_turns', models.FloatField(default=0, help_text='30天平均回合数', verbose_name='30天平均回合数')),
                ('Deck_deck_id', models.CharField(default='', help_text='卡组id', max_length=200, verbose_name='卡组id')),
                ('Deck_deck_list', models.CharField(default='', help_text='卡组', max_length=200, verbose_name='卡组')),
                ('Deck_digest', models.CharField(default='', help_text='未知', max_length=200, verbose_name='未知')),
                ('Deck_total_games', models.FloatField(default=0, help_text='近30天对局样本', verbose_name='近30天总对局样本')),
                ('Deck_win_rate', models.FloatField(default=0, help_text='近30天总对局样本胜率', verbose_name='近30天总对局样本胜率')),
                ('Group_as_of_info', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='卡组信息更新时间', max_length=100, null=True, verbose_name='卡组信息更新时间')),
            ],
            options={
                'verbose_name': '套牌信息',
                'verbose_name_plural': '套牌信息',
            },
        ),
        migrations.CreateModel(
            name='Deck_Scheduling_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Deck_deck_id', models.CharField(default='', help_text='卡组id', max_length=200, verbose_name='卡组id')),
                ('Card_dbf_id', models.FloatField(default=0, help_text='卡牌dbf_id', verbose_name='卡牌dbf_id')),
                ('Card_avg_turn_played_on', models.FloatField(default=0, help_text='卡牌打出平均回合', verbose_name='卡牌打出平均回合')),
                ('Card_avg_turns_in_hand', models.FloatField(default=0, help_text='卡牌留在手中平均回合', verbose_name='卡牌留在手中平均回合')),
                ('Card_keep_percentage', models.FloatField(default=0, help_text='保留率', verbose_name='保留率')),
                ('Card_opening_hand_winrate', models.FloatField(default=0, help_text='起手胜率', verbose_name='起手胜率')),
                ('Card_winrate_when_drawn', models.FloatField(default=0, help_text='抽到胜率', verbose_name='抽到胜率')),
                ('Card_winrate_when_played', models.FloatField(default=0, help_text='打出胜率', verbose_name='打出胜率')),
                ('Deck_UP_time', models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='卡组对抗更新时间', max_length=100, null=True, verbose_name='卡组对抗更新时间')),
            ],
            options={
                'verbose_name': '卡组卡牌调度',
                'verbose_name_plural': '卡组卡牌调度',
            },
        ),
        migrations.AlterModelOptions(
            name='card_duikang',
            options={'verbose_name': '卡组原型，对抗胜率', 'verbose_name_plural': '卡组原型，对抗胜率'},
        ),
        migrations.RemoveField(
            model_name='card_group',
            name='Group_as_of_info',
        ),
        migrations.RemoveField(
            model_name='card_group',
            name='Group_pct_of_class',
        ),
        migrations.RemoveField(
            model_name='card_group',
            name='Group_pct_of_total',
        ),
        migrations.RemoveField(
            model_name='card_group',
            name='Group_total_games',
        ),
        migrations.RemoveField(
            model_name='card_group',
            name='Group_win_rate',
        ),
        migrations.AlterField(
            model_name='card_duikang',
            name='upda_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='原型对局信息更新时间', max_length=100, null=True, verbose_name='原型对局信息更新时间'),
        ),
        migrations.AlterField(
            model_name='card_group',
            name='Group_as_of',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='原型加入时间', max_length=100, null=True, verbose_name='更新时间'),
        ),
    ]
