# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-02 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_auto_20190802_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck_info',
            name='Deck_code',
            field=models.CharField(default='', help_text='卡组代码', max_length=200, verbose_name='卡组代码'),
        ),
    ]
