# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-09 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20190809_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='player_class',
            name='zhiye_zhongwen',
            field=models.CharField(default='', help_text='职业中文', max_length=200, verbose_name='职业中文'),
        ),
    ]
