# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_deck_info_cost_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_cards',
            name='card_set',
            field=models.CharField(blank=True, default='', help_text='基础卡（CORE）,经典（EXPERT1），（奥丹姆）ULDUM，暗影崛起（DALARAN），拉斯塔哈的大乱斗（TROLL），砰砰计划（BOOMSDAY），女巫森林（GILNEAS），狗头人与地下世界（LOOTAPALOOZA），冰封的王座（ICECROWN），勇闯安戈洛（UNGORO），龙争虎斗加基森（GANGS），卡拉赞之夜（KARA），上古之神的低语（OG），探险者协会（LOE），冠军的试炼（TGT），黑石山的火焰（BRM），地精大战侏儒（GVG），纳克萨玛斯（NAXX），荣誉室（HOF）', max_length=200, verbose_name='属于扩展包'),
        ),
    ]
