# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_auto_20190819_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_duikang',
            name='Group_id',
            field=models.CharField(default='', help_text='原型名称', max_length=200, verbose_name='原型名称'),
        ),
    ]
