# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_auto_20190819_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card_group',
            name='id',
        ),
        migrations.AlterField(
            model_name='card_group',
            name='Group_id',
            field=models.IntegerField(blank=True, default=0, primary_key=True, serialize=False, verbose_name='原型ID'),
        ),
    ]
