# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 11:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0026_auto_20190819_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_duikang',
            name='Group_id',
            field=models.ForeignKey(help_text='原型id', on_delete=django.db.models.deletion.CASCADE, to='cards.Card_group', verbose_name='原型id'),
        ),
    ]
