# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0027_auto_20190819_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_group',
            name='Group_pct_of_class',
            field=models.FloatField(blank=True, default=0, help_text='近七天原型占该职业的套牌的百分比', verbose_name='近七天原型占该职业的套牌的百分比'),
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_pct_of_total',
            field=models.FloatField(blank=True, default=0, help_text='近七天原型占所有的套牌的百分比', verbose_name='近七天原型占所有的套牌的百分比'),
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_total_games',
            field=models.FloatField(blank=True, default=0, help_text='近七天原型总对局', verbose_name='近七天原型总对局'),
        ),
        migrations.AddField(
            model_name='card_group',
            name='Group_win_rate',
            field=models.FloatField(blank=True, default=0, help_text='近七天原型总对局胜率', verbose_name='近七天原型总对局胜率'),
        ),
    ]
