# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-19 12:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0028_auto_20190819_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_group',
            name='Group_mas_of_info',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, help_text='原型对局信息更新时间', max_length=100, null=True, verbose_name='原型对局信息更新时间'),
        ),
    ]
