# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0030_auto_20190819_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='card_group',
            name='Group_image',
            field=models.CharField(default='', max_length=500, verbose_name='原型图片'),
        ),
    ]
