# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-21 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0031_card_group_group_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card_duikang',
            name='hit_Group_id',
            field=models.IntegerField(default=0, help_text='原型对抗id', verbose_name='原型对抗id'),
        ),
    ]
