# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-08-30 01:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0032_auto_20190821_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_cards',
            name='jjc_update_time',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='更新时间', verbose_name='更新时间'),
        ),
    ]
